# Generated by Django 6.0.5 on 2026-05-16 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(help_text='2-letter state code, e.g. MA', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, help_text='Full address used for geocoding', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(help_text='0.0 - 5.0')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['state', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='Shoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipedrive_deal_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('shoot_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=120)),
                ('status', models.CharField(choices=[('pending', 'Pending - looking for videographer'), ('confirmed', 'Confirmed'), ('failed', 'Failed - no one accepted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_videographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_shoots', to='scheduler.videographer')),
            ],
            options={
                'ordering': ['-shoot_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='Order in the ranked list (0 = top pick)')),
                ('score', models.FloatField(help_text='Score at time of ranking (rating - penalty*drive_min)')),
                ('drive_minutes', models.FloatField(blank=True, null=True)),
                ('drive_miles', models.FloatField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired (no response in 24h)'), ('cancelled', 'Cancelled (someone else accepted)')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='scheduler.shoot')),
                ('videographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='scheduler.videographer')),
            ],
            options={
                'ordering': ['shoot', 'rank'],
                'unique_together': {('shoot', 'videographer')},
            },
        ),
    ]
