# Generated by Django 6.0.5 on 2026-05-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_penalty_per_minute', models.FloatField(default=0.01, help_text='Rating points deducted per minute of estimated drive time. 0.01 = balanced. 0.02 = distance matters a lot. 0.005 = rating wins almost always.')),
                ('max_drive_minutes', models.IntegerField(default=180, help_text='Hard cap: skip any videographer whose drive time exceeds this.')),
                ('escalation_hours', models.FloatField(default=24.0, help_text='How long to wait for a videographer to accept before escalating to next ranked person.')),
                ('same_state_only', models.BooleanField(default=True, help_text='If checked, only consider videographers from the same state as the shoot.')),
            ],
            options={
                'verbose_name': 'Scheduling Settings',
                'verbose_name_plural': 'Scheduling Settings',
            },
        ),
    ]
