# Generated by Django 6.0.5 on 2026-05-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_schedulingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingsettings',
            name='activity_type_filter',
            field=models.CharField(blank=True, default='Shoot Booking', help_text='Only Pipedrive activities whose type name CONTAINS this string will trigger a booking. Leave blank to trigger on all activities.', max_length=100),
        ),
    ]
