# Generated by Django 6.0.5 on 2026-05-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_schedulingsettings_activity_type_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoot',
            name='pipedrive_activity_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pipedrive activity id — used to look up shoot on delete webhooks (which omit deal_id)', max_length=50, null=True),
        ),
    ]
