# Generated by Django 6.0.5 on 2026-05-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_shoot_pipedrive_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoot',
            name='pipedrive_activity_id',
            field=models.CharField(blank=True, help_text='Pipedrive activity id — the actual unique identifier for one shoot', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shoot',
            name='pipedrive_deal_id',
            field=models.CharField(blank=True, db_index=True, help_text='Pipedrive deal id (a deal can have multiple shoot activities — NOT unique)', max_length=50, null=True),
        ),
    ]
