# Generated by Django 6.0.5 on 2026-06-10 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_shoot_pipedrive_activity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.FloatField(default=5.0, help_text='0.0 - 5.0')),
                ('max_active_jobs', models.PositiveIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='schedulingsettings',
            name='edit_activity_type_filter',
            field=models.CharField(blank=True, default='Recruiting Highlight Video,Hype Video,Highlight Recap', help_text='Comma-separated Pipedrive activity type names that trigger edit jobs.', max_length=100),
        ),
        migrations.AddField(
            model_name='schedulingsettings',
            name='edit_subject_filter',
            field=models.CharField(blank=True, default='', help_text='Optional extra subject filter for edit jobs. Leave blank when using dedicated edit activity types.', max_length=100),
        ),
        migrations.AddField(
            model_name='schedulingsettings',
            name='edit_workload_penalty',
            field=models.FloatField(default=0.75, help_text='Rating points deducted per active edit job when choosing an editor.'),
        ),
        migrations.CreateModel(
            name='EditJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipedrive_deal_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('pipedrive_activity_id', models.CharField(blank=True, help_text='Pipedrive activity id - the unique identifier for one edit job', max_length=50, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('due_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('failed', 'Failed - no editor available'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('active_job_count_at_assignment', models.PositiveIntegerField(default=0)),
                ('assignment_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_jobs', to='scheduler.editor')),
            ],
            options={
                'ordering': ['due_datetime'],
            },
        ),
    ]
