# Generated by Django 6.0.5 on 2026-06-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_editor_schedulingsettings_edit_activity_type_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editjob',
            name='selection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='editjob',
            name='video_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
