# Generated by Django 6.0.5 on 2026-06-10 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_editjob_selection_reason_editjob_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editjob',
            name='video_type',
            field=models.CharField(blank=True, choices=[('Highlight', 'Highlight'), ('Hype', 'Hype'), ('Recruiting', 'Recruiting')], max_length=30),
        ),
        migrations.CreateModel(
            name='EditorVideoTypeRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('Highlight', 'Highlight'), ('Hype', 'Hype'), ('Recruiting', 'Recruiting')], max_length=30)),
                ('rank', models.PositiveIntegerField(help_text='1 is the first choice for this video type.')),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_type_ranks', to='scheduler.editor')),
            ],
            options={
                'ordering': ['video_type', 'rank', 'editor__name'],
                'unique_together': {('editor', 'video_type'), ('video_type', 'rank')},
            },
        ),
    ]
