# Generated by Django 6.0.5 on 2026-06-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_editjob_video_type_editorvideotyperank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='editjob',
            name='assignment_score',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='schedulingsettings',
            name='edit_workload_penalty',
        ),
    ]
