# Generated by Django 6.0.5 on 2026-06-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_alter_editor_options_remove_editjob_assignment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editjob',
            name='clickup_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='editjob',
            name='clickup_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editjob',
            name='clickup_task_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='editor',
            name='clickup_user_id',
            field=models.BigIntegerField(blank=True, help_text='ClickUp user ID used when assigning edit tasks.', null=True),
        ),
        migrations.AlterField(
            model_name='editjob',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('failed', 'Failed - no editor available'), ('clickup_failed', 'Failed - ClickUp task not created'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
