# Generated by Django 6.0.5 on 2026-06-29 21:40

import django.db.models.deletion
from django.db import migrations, models


def seed_home_service_states(apps, schema_editor):
    Videographer = apps.get_model('scheduler', 'Videographer')
    VideographerServiceState = apps.get_model('scheduler', 'VideographerServiceState')
    for videographer in Videographer.objects.exclude(state=''):
        VideographerServiceState.objects.get_or_create(
            videographer=videographer,
            state=videographer.state,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_seed_editor_rankings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videographer',
            name='state',
            field=models.CharField(help_text='2-letter home/base state, e.g. MA', max_length=2),
        ),
        migrations.CreateModel(
            name='VideographerServiceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CT', 'Connecticut'), ('DE', 'Delaware'), ('MA', 'Massachusetts'), ('ME', 'Maine'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NY', 'New York'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('VT', 'Vermont')], max_length=2)),
                ('videographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_states', to='scheduler.videographer')),
            ],
            options={
                'ordering': ['state', 'videographer__name'],
                'unique_together': {('videographer', 'state')},
            },
        ),
        migrations.RunPython(seed_home_service_states, noop_reverse),
    ]
