# Generated by Django 6.0.5 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0012_alter_videographer_state_videographerservicestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoot",
            name="google_drive_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="shoot",
            name="google_drive_folder_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="shoot",
            name="google_drive_folder_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="google_drive_permission_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]

