# Generated by Django 6.0.5 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0013_shoot_google_drive_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="calendar_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="calendar_last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

